import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync } from 'node:fs';
import worker from '../dist/server/index.js';
const base='https://portfolio.example';
const auth={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'ameliashap@gmail.com'};
function env(){const db=new DatabaseSync(':memory:'); for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql'))) db.exec(readFileSync('drizzle/'+f,'utf8'));return {DB:{prepare(sql){return {bind(...args){const q=db.prepare(sql);return {first:async()=>q.get(...args),all:async()=>({results:q.all(...args)}),run:async()=>({meta:q.run(...args)})};}}}},db};}
function submit(data={},headers={}){return new Request(base+'/api/contact',{method:'POST',headers:{origin:base,'content-type':'application/json',...headers},body:JSON.stringify({name:'Visitor',email:'visitor@example.org',message:'Hello Amelia',...data})});}
test('save, retry, and render messages only to owner with escaped markup',async()=>{const e=env(),id=crypto.randomUUID();assert.equal((await worker.fetch(submit({id,message:'<script>alert(1)</script>'}),e)).status,200);assert.equal((await worker.fetch(submit({id}),e)).status,200);assert.equal(e.db.prepare('SELECT COUNT(*) n FROM contact_messages').get().n,1);const inbox=await worker.fetch(new Request(base+'/inbox',{headers:auth}),e);assert.match(await inbox.text(),/&lt;script&gt;/);assert.equal((await worker.fetch(new Request(base+'/inbox'),e)).status,302);assert.equal((await worker.fetch(new Request(base+'/inbox',{headers:{...auth,'oai-authenticated-user-email':'other@example.org'}}),e)).status,403);});
test('invalid, cross-origin and oversized submissions are rejected',async()=>{const e=env();assert.equal((await worker.fetch(submit({email:'bad'}),e)).status,400);assert.equal((await worker.fetch(submit({}, {origin:'https://other.example'}),e)).status,403);assert.equal((await worker.fetch(submit({message:'a'.repeat(33000)}),e)).status,413);assert.equal(e.db.prepare('SELECT COUNT(*) n FROM contact_messages').get().n,0);});
test('limits repeated submissions and reports database failure',async()=>{const e=env();for(let i=0;i<5;i++)assert.equal((await worker.fetch(submit(),e)).status,200);assert.equal((await worker.fetch(submit(),e)).status,429);assert.equal((await worker.fetch(submit(),{})).status,503);});
test('native form and portfolio assets work',async()=>{const e=env();const r=await worker.fetch(new Request(base+'/api/contact',{method:'POST',headers:{origin:base,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:'Visitor',email:'visitor@example.org',message:'Hello'})}),e);assert.equal(r.status,303);const page=await worker.fetch(new Request(base),e);assert.match(await page.text(),/id="contact-form"/);assert.equal((await worker.fetch(new Request(base+'/amelia-shapiro-portrait.jpeg'),e)).status,200);});
